# Do not change the 'definitions' section unless you know what you're doing
asset_store:
  synapse:
    master_fileview_id: 'syn16858331'
    manifest_basename: 'synapse_storage_manifest'

manifest:
  manifest_folder: 'manifests'
  title: Data Manifest
  data_type: 
  - GenomicsAssayTemplate

model:
  location: './NF.jsonld'

google_sheets:
  service_acct_creds: "creds.json"
  strict_validation: true

