#!/usr/bin/env python3
"""
Tests for the annotation key policy used to clean up mis-cased annotation keys
on NF-OSI Synapse entities (issue #939).

Every test here is offline. The policy module deliberately does not import
synapseclient, so the decision rules that govern destructive writes can be
exercised in CI without credentials or network access.

Two independent classifiers are under test:

* Rule A - a legacy schematic path keyed annotations off the schema's PascalCase
  ``rdfs:label`` instead of the camelCase ``sms:displayName``, leaving pairs like
  ``Age``/``age`` on the same entity.
* Rule B - case-insensitive collision, which catches former slot names left
  behind by schema renames (``timePointUnit`` -> ``timepointUnit``). Rule A
  cannot see these at all.
"""

import json
import os
import sys
from pathlib import Path

import pytest

utils_path = os.path.join(os.path.dirname(__file__), '..', 'utils')
sys.path.insert(0, utils_path)

import annotation_key_policy as policy  # noqa: E402  (needs utils on sys.path first)

REPO_ROOT = Path(__file__).resolve().parent.parent
FIXTURE_DIR = Path(__file__).parent / 'data' / 'annotation_keys'


@pytest.fixture(scope='module')
def canon():
    return policy.load_canonical_slots()


@pytest.fixture(scope='module')
def index(canon):
    return policy.KeyIndex.build(canon)


# ---------------------------------------------------------------------------
# Canonical slot loading
# ---------------------------------------------------------------------------

def test_load_canonical_slots_includes_both_slots_and_inline_attributes(canon):
    # 262 names come from the top-level `slots:` block.
    assert 'age' in canon
    assert 'specimenID' in canon
    # 39 more are declared as inline `attributes:` on 5 template classes and are
    # absent from `slots:`. Missing them would make the audit blind to portal
    # study/dataset/publication annotations.
    for attribute_only in ('keywords', 'funder', 'pmid', 'individualCount', 'measurementTechnique'):
        assert attribute_only in canon, f'{attribute_only} is declared via class attributes'
    assert len(canon) == 301


def test_load_canonical_slots_reads_dist_not_legacy_jsonld():
    # NF.jsonld is legacy and no longer regenerated by the build; dist/NF.yaml is
    # the source of truth. Guard against a silent reversion.
    assert policy.CANONICAL_SCHEMA == REPO_ROOT / 'dist' / 'NF.yaml'
    assert policy.CANONICAL_SCHEMA.exists()


# ---------------------------------------------------------------------------
# Rule A: PascalCase derivation
# ---------------------------------------------------------------------------

@pytest.mark.parametrize('canonical,stray', [
    ('age', 'Age'),
    ('ageUnit', 'AgeUnit'),
    ('sex', 'Sex'),
    ('organ', 'Organ'),
    ('comments', 'Comments'),
    ('specimenID', 'SpecimenID'),
    ('individualID', 'IndividualID'),
    ('dataSubtype', 'DataSubtype'),
    # The awkward ones. Each of these was observed on real entities, so the
    # derivation rule has to reproduce them exactly.
    ('nf1Genotype', 'Nf1Genotype'),
    ('nf2Genotype', 'Nf2Genotype'),
    ('nFiles', 'NFiles'),
    ('grantDOI', 'GrantDOI'),
    ('isFilteredReads', 'IsFilteredReads'),
])
def test_to_stray_reproduces_observed_pascal_keys(canonical, stray):
    assert policy.to_stray(canonical) == stray


def test_to_stray_is_identity_for_already_capitalised_names():
    assert policy.to_stray('Component') == 'Component'
    assert policy.to_stray('GIST') == 'GIST'


def test_to_stray_handles_empty_string():
    assert policy.to_stray('') == ''


# ---------------------------------------------------------------------------
# Stray index invariants, checked against the real schema
# ---------------------------------------------------------------------------

def test_stray_index_never_maps_a_name_to_itself(index):
    for stray, canonical in index.stray_index.items():
        assert stray != canonical, f'{stray} would be renamed to itself'


def test_stray_index_excludes_self_pascal_canonical_slots(index, canon):
    # These 9 canonical slots already start uppercase, so to_stray() is the
    # identity. Without the guard the tool flags valid `Component` data as a
    # stray and tries to rename it to itself.
    self_pascal = {c for c in canon if policy.to_stray(c) == c}
    assert self_pascal == {
        'Component', 'Filename', 'GIST', 'InChIKey', 'IrisLischNodules',
        'MPNSTCharacterization', 'MRISequence', 'Resource_id', 'WHOPerformanceStatus',
    }
    for name in self_pascal:
        assert name not in index.stray_index


def test_stray_index_values_are_all_canonical(index, canon):
    for canonical in index.stray_index.values():
        assert canonical in canon


def test_no_two_canonical_names_collide_onto_one_stray(canon):
    # True today. If a schema change breaks it, a stray key becomes ambiguous
    # and must not be auto-renamed, so this needs to fail loudly.
    seen = {}
    for name in canon:
        stray = policy.to_stray(name)
        if stray == name:
            continue
        assert stray not in seen, f'{stray} maps to both {seen.get(stray)} and {name}'
        seen[stray] = name


def test_legacy_aliases_resolve_to_current_canonical_names(index, canon):
    # Five verified exceptions the PascalCase rule cannot derive. They have zero
    # hits in the wild today; they are kept so coverage claims stay honest.
    assert policy.LEGACY_ALIASES == {
        'Breast Cancer': 'breastCancer',
        'Vestibular Schwannoma': 'vestibularSchwannoma',
        'CroissantFileS3Object': 'croissant_file_s3_object',
        'ResourceId': 'Resource_id',
        'eTag': 'etag',
    }
    for target in policy.LEGACY_ALIASES.values():
        assert target in canon


# ---------------------------------------------------------------------------
# Reserved Synapse entity fields
# ---------------------------------------------------------------------------

def test_all_reserved_field_names_exist_in_canon(canon):
    # A regression guard in both directions: if the schema drops one of these the
    # guard silently retires, and if Synapse adds a reserved name we need to add
    # it here deliberately.
    assert policy.SYNAPSE_RESERVED_FIELDS <= canon
    assert len(policy.SYNAPSE_RESERVED_FIELDS) == 15


@pytest.mark.parametrize('stray', ['Description', 'Name', 'Type', 'ParentId', 'ContentType'])
def test_orphan_stray_targeting_a_reserved_field_is_never_renamed(stray, canon, index):
    decision = policy.decide(stray, {stray: ['a real value']}, canon=canon, index=index)
    assert decision.action == policy.Action.REPORT_RESERVED
    assert decision.canonical_key in policy.SYNAPSE_RESERVED_FIELDS


# ---------------------------------------------------------------------------
# Infrastructure keys
# ---------------------------------------------------------------------------

@pytest.mark.parametrize('key', ['Id', 'Uuid', 'EntityId', 'entityId', 'eTag'])
def test_schematic_infra_keys_are_skipped(key, canon, index):
    # `Id` alone produced 55 false-positive projects before it was allowlisted:
    # it is a schematic manifest UUID, not a stray form of the `id` slot.
    decision = policy.decide(key, {key: ['x']}, canon=canon, index=index)
    assert decision.action == policy.Action.SKIP
    assert decision.reason == 'infra_key'


@pytest.mark.parametrize('key', ['Component', 'Filename', 'age', 'specimenID'])
def test_canonical_keys_need_no_action(key, canon, index):
    decision = policy.decide(key, {key: ['x']}, canon=canon, index=index)
    assert decision.action == policy.Action.SKIP
    assert decision.reason == 'canonical'


def test_unknown_key_is_skipped_but_flagged(canon, index):
    decision = policy.decide('TotallyMadeUpKey', {'TotallyMadeUpKey': ['x']}, canon=canon, index=index)
    assert decision.action == policy.Action.SKIP
    assert decision.reason == 'unknown_key'


# ---------------------------------------------------------------------------
# Value comparison
# ---------------------------------------------------------------------------

def test_scalar_and_single_item_list_are_equivalent():
    assert policy.values_equivalent([1.5], 1.5)
    assert policy.values_equivalent('brain', ['brain'])


def test_int_and_string_forms_differ_strictly_but_match_loosely():
    # The real syn64420376 case: IndividualID is INTEGER 1119 while
    # individualID is STRING "1119". Equal in intent, unequal in type.
    assert not policy.values_equivalent([1119], ['1119'])
    assert policy.values_equivalent([1119], ['1119'], loose=True)
    assert policy.values_equivalent([1.0], ['1'], loose=True)


def test_numerically_identical_values_are_strictly_equivalent():
    assert policy.values_equivalent([1], [1.0])


def test_list_order_matters_strictly_but_not_loosely():
    # Conservative on purpose: a reordered list is reported for review rather
    # than silently treated as a duplicate and deleted.
    assert not policy.values_equivalent(['a', 'b'], ['b', 'a'])
    assert policy.values_equivalent(['a', 'b'], ['b', 'a'], loose=True)


def test_booleans_match_their_string_form_only_loosely():
    assert not policy.values_equivalent([True], ['true'])
    assert policy.values_equivalent([True], ['true'], loose=True)


def test_whitespace_is_stripped_before_comparison():
    assert policy.values_equivalent(['  brain '], ['brain'])


def test_truncated_values_are_never_equivalent():
    # Executable documentation of why an EntityView is unsafe as a comparison
    # source: view STRING columns are declared at maximum_size=80, so a longer
    # value comes back truncated. Deciding "equal, drop one" from a truncated
    # read could destroy the only surviving copy.
    long_value = 'x' * 200
    assert not policy.values_equivalent([long_value], [long_value[:80]])
    assert not policy.values_equivalent([long_value], [long_value[:80]], loose=True)


@pytest.mark.parametrize('empty', [None, [], [''], ['   '], [None], ''])
def test_empty_value_detection(empty):
    assert policy.is_empty_value(empty)


@pytest.mark.parametrize('present', [[0], [False], ['x'], 0, False])
def test_zero_and_false_are_not_empty(present):
    # Dropping a legitimate 0 or False as if it were absent would lose data.
    assert not policy.is_empty_value(present)


# ---------------------------------------------------------------------------
# Decision table
# ---------------------------------------------------------------------------

def test_duplicate_with_identical_value_is_dropped(canon, index):
    annotations = {'Age': [1.5], 'age': [1.5]}
    decision = policy.decide('Age', annotations, canon=canon, index=index)
    assert decision.action == policy.Action.DROP_STRAY
    assert decision.canonical_key == 'age'
    assert decision.reason == 'values_equivalent'


def test_duplicate_differing_only_in_type_is_reported_not_dropped(canon, index):
    annotations = {'IndividualID': [1119], 'individualID': ['1119']}
    decision = policy.decide('IndividualID', annotations, canon=canon, index=index)
    assert decision.action == policy.Action.REPORT_CONFLICT
    assert decision.reason == 'type_coercion'


def test_loose_compare_promotes_type_coercion_to_a_drop(canon, index):
    annotations = {'IndividualID': [1119], 'individualID': ['1119']}
    decision = policy.decide('IndividualID', annotations, canon=canon, index=index, loose_compare=True)
    assert decision.action == policy.Action.DROP_STRAY


def test_duplicate_with_genuinely_different_values_is_never_touched(canon, index):
    annotations = {'Organ': ['nerves'], 'organ': ['brain']}
    decision = policy.decide('Organ', annotations, canon=canon, index=index)
    assert decision.action == policy.Action.REPORT_CONFLICT
    assert decision.reason == 'values_differ'


def test_empty_canonical_alongside_populated_stray_is_reported(canon, index):
    annotations = {'Sex': ['Female'], 'sex': []}
    decision = policy.decide('Sex', annotations, canon=canon, index=index)
    assert decision.action == policy.Action.REPORT_CONFLICT
    assert decision.reason == 'canonical_empty'


def test_empty_stray_is_dropped_even_when_the_canonical_value_differs(canon, index):
    # Ordering matters: the empty check has to run before value comparison, or an
    # empty stray next to a populated canonical is misfiled as a conflict and
    # the noise is never cleaned up.
    annotations = {'Organ': [''], 'organ': ['nerves']}
    decision = policy.decide('Organ', annotations, canon=canon, index=index)
    assert decision.action == policy.Action.DROP_STRAY
    assert decision.reason == 'empty_stray_value'


def test_empty_stray_targeting_a_reserved_field_is_still_droppable(canon, index):
    # Removing a stray `Description` key does not write to the reserved
    # `description` entity property, so dropping empty noise is safe.
    decision = policy.decide('Description', {'Description': ['']}, canon=canon, index=index)
    assert decision.action == policy.Action.DROP_STRAY


def test_duplicate_reserved_name_with_equal_values_is_dropped(canon, index):
    # Real case in syn51356705: both `ContentType` and `contentType` are present.
    # Dropping the stray is safe because nothing is written to the reserved name.
    annotations = {'ContentType': ['dataset'], 'contentType': ['dataset']}
    decision = policy.decide('ContentType', annotations, canon=canon, index=index)
    assert decision.action == policy.Action.DROP_STRAY


def test_orphan_stray_is_renamed_to_the_canonical_name(canon, index):
    annotations = {'Nf2Genotype': ['-/-']}
    decision = policy.decide('Nf2Genotype', annotations, canon=canon, index=index)
    assert decision.action == policy.Action.RENAME_STRAY
    assert decision.canonical_key == 'nf2Genotype'


def test_orphan_with_a_third_case_variant_present_is_reported(canon, index):
    # Real case in syn8012530, which carries both `TimePointUnit` and
    # `timePointUnit`. Renaming either would silently clobber the other.
    annotations = {'TimePointUnit': ['days'], 'timePointUnit': ['weeks']}
    decision = policy.decide('TimePointUnit', annotations, canon=canon, index=index)
    assert decision.action == policy.Action.REPORT_CONFLICT
    assert decision.reason == 'multi_variant'


def test_alias_pointing_at_a_retired_slot_is_reported_not_renamed(canon, index):
    # Renaming into a slot the schema no longer defines would resurrect a dead
    # field into the portal namespace.
    shrunk = frozenset(canon - {'nf2Genotype'})
    shrunk_index = policy.KeyIndex.build(canon)  # index still knows the old mapping
    decision = policy.decide('Nf2Genotype', {'Nf2Genotype': ['-/-']}, canon=shrunk, index=shrunk_index)
    assert decision.action == policy.Action.REPORT_RETIRED


# ---------------------------------------------------------------------------
# Rule B: case-variant drift (family 2)
# ---------------------------------------------------------------------------

@pytest.mark.parametrize('variant,canonical', [
    ('timePointUnit', 'timepointUnit'),
    ('specimenIdSource', 'specimenIDSource'),
    ('experimentalTimePoint', 'experimentalTimepoint'),
    ('studyID', 'studyId'),
    ('dataSubType', 'dataSubtype'),
    ('individualId', 'individualID'),
    ('parentSpecimenId', 'parentSpecimenID'),
    ('component', 'Component'),
    ('filename', 'Filename'),
])
def test_case_variant_drift_resolves_to_the_canonical_slot(variant, canonical, canon, index):
    # None of these are derivable from the PascalCase rule; they are former slot
    # names left behind by schema renames and are only caught by rule B.
    resolved, rule = policy.resolve_canonical(variant, canon=canon, index=index)
    assert resolved == canonical
    assert rule == 'case_variant'


def test_orphan_case_variant_is_renamed(canon, index):
    decision = policy.decide('timePointUnit', {'timePointUnit': ['days']}, canon=canon, index=index)
    assert decision.action == policy.Action.RENAME_STRAY
    assert decision.canonical_key == 'timepointUnit'


def test_pascal_rule_alone_would_miss_etag(canon, index):
    # to_stray('etag') is 'Etag', not 'eTag', so only the alias table catches it.
    assert policy.to_stray('etag') == 'Etag'
    resolved, _ = policy.resolve_canonical('eTag', canon=canon, index=index)
    assert resolved == 'etag'


# ---------------------------------------------------------------------------
# decide_entity and apply_decisions
# ---------------------------------------------------------------------------

def test_decide_entity_covers_the_real_syn64420376_annotations(canon, index):
    annotations = json.loads((FIXTURE_DIR / 'syn64420376_annotations.json').read_text())
    decisions = {d.stray_key: d for d in policy.decide_entity(annotations, canon=canon, index=index)}

    for stray, canonical in [('Age', 'age'), ('Sex', 'sex'), ('Assay', 'assay'),
                             ('Organ', 'organ'), ('AgeUnit', 'ageUnit'), ('Species', 'species'),
                             ('Comments', 'comments'), ('DataType', 'dataType'),
                             ('Platform', 'platform'), ('Diagnosis', 'diagnosis'),
                             ('TumorType', 'tumorType'), ('FileFormat', 'fileFormat'),
                             ('DataSubtype', 'dataSubtype'), ('ResourceType', 'resourceType'),
                             ('ModelSystemName', 'modelSystemName')]:
        assert decisions[stray].action == policy.Action.DROP_STRAY, stray
        assert decisions[stray].canonical_key == canonical

    # INTEGER 1119 vs STRING "1119" - reported, not silently dropped.
    assert decisions['IndividualID'].action == policy.Action.REPORT_CONFLICT
    assert decisions['IndividualID'].reason == 'type_coercion'

    # Schematic infrastructure and canonical keys are left alone.
    assert decisions['Id'].action == policy.Action.SKIP
    assert decisions['EntityId'].action == policy.Action.SKIP
    assert decisions['Component'].action == policy.Action.SKIP


def test_apply_decisions_drops_only_the_named_key(canon, index):
    annotations = {'Age': [1.5], 'age': [1.5], 'sex': ['Female']}
    decisions = [policy.decide('Age', annotations, canon=canon, index=index)]
    result = policy.apply_decisions(annotations, decisions)
    assert result == {'age': [1.5], 'sex': ['Female']}


def test_apply_decisions_renames_by_moving_the_value(canon, index):
    annotations = {'Nf2Genotype': ['-/-'], 'age': [1.5]}
    decisions = [policy.decide('Nf2Genotype', annotations, canon=canon, index=index)]
    result = policy.apply_decisions(annotations, decisions)
    assert result == {'nf2Genotype': ['-/-'], 'age': [1.5]}


def test_apply_decisions_does_not_mutate_its_input(canon, index):
    annotations = {'Age': [1.5], 'age': [1.5]}
    before = dict(annotations)
    policy.apply_decisions(annotations, [policy.decide('Age', annotations, canon=canon, index=index)])
    assert annotations == before


def test_apply_decisions_ignores_report_only_actions(canon, index):
    annotations = {'Organ': ['nerves'], 'organ': ['brain']}
    decisions = [policy.decide('Organ', annotations, canon=canon, index=index)]
    assert policy.apply_decisions(annotations, decisions) == annotations


def test_apply_decisions_is_idempotent(canon, index):
    annotations = {'Age': [1.5], 'age': [1.5]}
    decisions = [policy.decide('Age', annotations, canon=canon, index=index)]
    once = policy.apply_decisions(annotations, decisions)
    twice = policy.apply_decisions(once, policy.decide_entity(once, canon=canon, index=index))
    assert once == twice


def test_apply_decisions_raises_on_a_key_that_is_no_longer_present():
    # Silently no-oping here would let a stale plan report success without
    # having changed anything.
    stale = policy.Decision(
        action=policy.Action.DROP_STRAY, stray_key='Age', canonical_key='age', reason='values_equivalent',
    )
    with pytest.raises(KeyError):
        policy.apply_decisions({'age': [1.5]}, [stale])


def test_rename_refuses_to_overwrite_an_existing_canonical_key():
    # Defence in depth: decide() already routes this to a conflict, but
    # apply_decisions must not clobber even if handed a bad plan.
    bad = policy.Decision(
        action=policy.Action.RENAME_STRAY, stray_key='Age', canonical_key='age', reason='orphan',
    )
    with pytest.raises(ValueError):
        policy.apply_decisions({'Age': [1.5], 'age': [2.0]}, [bad])


# ---------------------------------------------------------------------------
# Real captured key inventories (offline, highest signal)
# ---------------------------------------------------------------------------

@pytest.mark.parametrize('project,expected_dup,expected_orphan', [
    ('syn25881328', 19, 4),
    ('syn35221462', 23, 20),
])
def test_captured_scope_columns_reproduce_the_measured_counts(project, expected_dup, expected_orphan, canon, index):
    columns = json.loads((FIXTURE_DIR / f'{project}_scope_columns.json').read_text())
    present = {c['name'] for c in columns}
    summary = policy.classify_key_inventory(present, canon=canon, index=index)
    assert len(summary.duplicates) == expected_dup, sorted(summary.duplicates)
    assert len(summary.orphans) == expected_orphan, sorted(summary.orphans)


def test_captured_inventory_never_flags_infra_keys(canon, index):
    columns = json.loads((FIXTURE_DIR / 'syn25881328_scope_columns.json').read_text())
    present = {c['name'] for c in columns}
    summary = policy.classify_key_inventory(present, canon=canon, index=index)
    flagged = set(summary.duplicates) | set(summary.orphans) | set(summary.case_variants)
    assert flagged.isdisjoint({'Id', 'Uuid', 'eTag', 'EntityId', 'entityId', 'Component', 'Filename'})


# ---------------------------------------------------------------------------
# Inventory hygiene: view metadata and near-miss typos
# ---------------------------------------------------------------------------

def test_default_view_columns_are_not_reported_as_unknown_keys(canon, index):
    # A view scope returns Synapse's own default columns alongside real
    # annotations. Reporting `modifiedOn` as an unrecognised annotation key
    # makes the unknown bucket noise, and noise gets ignored.
    summary = policy.classify_key_inventory(
        {'modifiedOn', 'projectId', 'versionNumber', 'dataFileName', 'tissue'},
        canon=canon, index=index,
    )
    assert 'modifiedOn' not in summary.unknown
    assert 'projectId' not in summary.unknown
    assert 'versionNumber' not in summary.unknown
    assert 'dataFileName' not in summary.unknown
    # A genuine custom annotation still lands in unknown.
    assert 'tissue' in summary.unknown


def test_near_miss_typo_is_separated_from_genuine_custom_annotations(canon, index):
    # Real key observed in syn51356705: `progrssReportNumber`, one character off
    # `progressReportNumber`. That is a data bug worth surfacing, whereas
    # `tissue` is a legitimate annotation outside the schema.
    summary = policy.classify_key_inventory(
        {'progrssReportNumber', 'tissue', 'sampleSite'}, canon=canon, index=index,
    )
    assert summary.near_misses == {'progrssReportNumber': 'progressReportNumber'}
    assert set(summary.unknown) == {'tissue', 'sampleSite'}


def test_near_miss_detection_can_be_disabled(canon, index):
    summary = policy.classify_key_inventory(
        {'progrssReportNumber'}, canon=canon, index=index, detect_typos=False,
    )
    assert summary.near_misses == {}
    assert summary.unknown == ['progrssReportNumber']


def test_near_misses_are_never_queued_for_a_write(canon, index):
    # A typo is not a case variant, so decide() must not try to repair it.
    decision = policy.decide('progrssReportNumber', {'progrssReportNumber': [3]},
                             canon=canon, index=index)
    assert decision.action == policy.Action.SKIP
    assert decision.reason == 'unknown_key'
