#!/usr/bin/env python3
"""
Add conditional enum filtering to generated JSON schemas.

This script post-processes LinkML-generated JSON schemas to add if/then/else
conditionals that filter modelSystemName enum values based on user selections
in modelSystemType, modelSpecies, cellLineCategory, and cellLineGeneticDisorder.

This enables the Synapse curator grid to show contextually relevant options
without hitting the 100-value enum limit.
"""

import json
import os
import sys
from pathlib import Path
from typing import Dict, List, Any


# Mapping of filter combinations to enum subset names
# Generated by analyzing the filtered enum files
CONDITIONAL_MAPPINGS = [
    # Cell Lines - Human - Cancer
    {
        "modelSystemType": "cell line",
        "modelSpecies": "Homo sapiens",
        "cellLineCategory": "Cancer cell line",
        "cellLineGeneticDisorder": "Neurofibromatosis type 1",
        "enum": "CellLineHomosapiensCancercelllineNeurofibromatosistype1Enum"
    },
    # Cell Lines - Human - iPSC
    {
        "modelSystemType": "cell line",
        "modelSpecies": "Homo sapiens",
        "cellLineCategory": "Induced pluripotent stem cell",
        "cellLineGeneticDisorder": "Neurofibromatosis type 1",
        "enum": "CellLineHomosapiensInducedpluripotentstemcellNeurofibromatosistype1Enum"
    },
    {
        "modelSystemType": "cell line",
        "modelSpecies": "Homo sapiens",
        "cellLineCategory": "Induced pluripotent stem cell",
        "cellLineGeneticDisorder": "No known genetic disorder",
        "enum": "CellLineHomosapiensInducedpluripotentstemcellNoknowngeneticdisorderEnum"
    },
    # Cell Lines - Human - Transformed
    {
        "modelSystemType": "cell line",
        "modelSpecies": "Homo sapiens",
        "cellLineCategory": "Transformed cell line",
        "cellLineGeneticDisorder": "Neurofibromatosistype 1",
        "enum": "CellLineHomosapiensTransformedcelllineNeurofibromatosistype1Enum"
    },
    {
        "modelSystemType": "cell line",
        "modelSpecies": "Homo sapiens",
        "cellLineCategory": "Transformed cell line",
        "cellLineGeneticDisorder": "No known genetic disorder",
        "enum": "CellLineHomosapiensTransformedcelllineNoknowngeneticdisorderEnum"
    },
    # Cell Lines - Human - Telomerase immortalized
    {
        "modelSystemType": "cell line",
        "modelSpecies": "Homo sapiens",
        "cellLineCategory": "Telomerase immortalized cell line",
        "cellLineGeneticDisorder": "Neurofibromatosis type 1",
        "enum": "CellLineHomosapiensTelomeraseimmortalizedcelllineNeurofibromatosistype1Enum"
    },
    {
        "modelSystemType": "cell line",
        "modelSpecies": "Homo sapiens",
        "cellLineCategory": "Telomerase immortalized cell line",
        "cellLineGeneticDisorder": "No known genetic disorder",
        "enum": "CellLineHomosapiensTelomeraseimmortalizedcelllineNoknowngeneticdisorderEnum"
    },
    # Cell Lines - Human - Embryonic stem cell
    {
        "modelSystemType": "cell line",
        "modelSpecies": "Homo sapiens",
        "cellLineCategory": "Embryonic stem cell",
        "cellLineGeneticDisorder": "Neurofibromatosis type 1",
        "enum": "CellLineHomosapiensEmbryonicstemcellNeurofibromatosistype1Enum"
    },
    # Cell Lines - Human - Finite cell line
    {
        "modelSystemType": "cell line",
        "modelSpecies": "Homo sapiens",
        "cellLineCategory": "Finite cell line",
        "cellLineGeneticDisorder": "Neurofibromatosis type 1",
        "enum": "CellLineHomosapiensFinitecelllineNeurofibromatosistype1Enum"
    },
    {
        "modelSystemType": "cell line",
        "modelSpecies": "Homo sapiens",
        "cellLineCategory": "Finite cell line",
        "cellLineGeneticDisorder": "No known genetic disorder",
        "enum": "CellLineHomosapiensFinitecelllineNoknowngeneticdisorderEnum"
    },
    # Cell Lines - Human - Other categories
    {
        "modelSystemType": "cell line",
        "modelSpecies": "Homo sapiens",
        "cellLineCategory": "Hybrid cell line",
        "cellLineGeneticDisorder": "No known genetic disorder",
        "enum": "CellLineHomosapiensHybridcelllineNoknowngeneticdisorderEnum"
    },
    {
        "modelSystemType": "cell line",
        "modelSpecies": "Homo sapiens",
        "cellLineCategory": "Spontaneously immortalized cell line",
        "cellLineGeneticDisorder": "No known genetic disorder",
        "enum": "CellLineHomosapiensSpontaneouslyimmortalizedcelllineNoknowngeneticdisorderEnum"
    },
    {
        "modelSystemType": "cell line",
        "modelSpecies": "Homo sapiens",
        "cellLineCategory": "Undefined cell line type",
        "cellLineGeneticDisorder": "Neurofibromatosis type 1",
        "enum": "CellLineHomosapiensUndefinedcelllinetypeNeurofibromatosistype1Enum"
    },
    # Cell Lines - Mouse
    {
        "modelSystemType": "cell line",
        "modelSpecies": "Mus musculus",
        "cellLineCategory": "Cancer cell line",
        "cellLineGeneticDisorder": "No known genetic disorder",
        "enum": "CellLineMusmusculusCancercelllineNoknowngeneticdisorderEnum"
    },
    {
        "modelSystemType": "cell line",
        "modelSpecies": "Mus musculus",
        "cellLineCategory": "Embryonic stem cell",
        "cellLineGeneticDisorder": "Neurofibromatosis type 1",
        "enum": "CellLineMusmusculusEmbryonicstemcellNeurofibromatosistype1Enum"
    },
    {
        "modelSystemType": "cell line",
        "modelSpecies": "Mus musculus",
        "cellLineCategory": "Embryonic stem cell",
        "cellLineGeneticDisorder": "No known genetic disorder",
        "enum": "CellLineMusmusculusEmbryonicstemcellNoknowngeneticdisorderEnum"
    },
    {
        "modelSystemType": "cell line",
        "modelSpecies": "Mus musculus",
        "cellLineCategory": "Induced pluripotent stem cell",
        "cellLineGeneticDisorder": "No known genetic disorder",
        "enum": "CellLineMusmusculusInducedpluripotentstemcellNoknowngeneticdisorderEnum"
    },
    {
        "modelSystemType": "cell line",
        "modelSpecies": "Mus musculus",
        "cellLineCategory": "Hybrid cell line",
        "cellLineGeneticDisorder": "No known genetic disorder",
        "enum": "CellLineMusmusculusHybridcelllineNoknowngeneticdisorderEnum"
    },
    {
        "modelSystemType": "cell line",
        "modelSpecies": "Mus musculus",
        "cellLineCategory": "Hybridoma",
        "cellLineGeneticDisorder": "No known genetic disorder",
        "enum": "CellLineMusmusculusHybridomaNoknowngeneticdisorderEnum"
    },
    {
        "modelSystemType": "cell line",
        "modelSpecies": "Mus musculus",
        "cellLineCategory": "Spontaneously immortalized cell line",
        "cellLineGeneticDisorder": "Neurofibromatosis type 1",
        "enum": "CellLineMusmusculusSpontaneouslyimmortalizedcelllineNeurofibromatosistype1Enum"
    },
    # Cell Lines - Other species
    {
        "modelSystemType": "cell line",
        "modelSpecies": "Canis lupus familiaris",
        "cellLineCategory": "Cancer cell line",
        "cellLineGeneticDisorder": "No known genetic disorder",
        "enum": "CellLineCanislupusfamiliarisCancercelllineNoknowngeneticdisorderEnum"
    },
    {
        "modelSystemType": "cell line",
        "modelSpecies": "Xenopus laevis",
        "cellLineCategory": "Spontaneously immortalized cell line",
        "cellLineGeneticDisorder": "No known genetic disorder",
        "enum": "CellLineXenopuslaevisSpontaneouslyimmortalizedcelllineNoknowngeneticdisorderEnum"
    },
    {
        "modelSystemType": "cell line",
        "modelSpecies": "Escherichia coli",
        "cellLineCategory": "Undefined cell line type",
        "cellLineGeneticDisorder": "No known genetic disorder",
        "enum": "CellLineEscherichiacoliUndefinedcelllinetypeNoknowngeneticdisorderEnum"
    },
    {
        "modelSystemType": "cell line",
        "modelSpecies": "Cricetulus griseus",
        "cellLineCategory": "Hybrid cell line",
        "cellLineGeneticDisorder": "No known genetic disorder",
        "enum": "CellLineCricetulusgriseusHybridcelllineNoknowngeneticdisorderEnum"
    },
    # Animal Models - simplified (no category for animal models)
    {
        "modelSystemType": "animal model",
        "modelSpecies": "Danio rerio",
        "enum": "AnimalModelDaniorerioNeurofibromatosistype1Enum"
    },
    {
        "modelSystemType": "animal model",
        "modelSpecies": "Drosophila melanogaster",
        "enum": "AnimalModelDrosophilamelanogasterNeurofibromatosistype1Enum"
    },
    {
        "modelSystemType": "animal model",
        "modelSpecies": "Sus scrofa",
        "enum": "AnimalModelSusscrofaNeurofibromatosistype1Enum"
    },
    {
        "modelSystemType": "animal model",
        "modelSpecies": "Saccharomyces cerevisiae",
        "enum": "AnimalModelSaccharomycescerevisiaeNeurofibromatosistype1Enum"
    },
]


def create_conditional_rule(mapping: Dict[str, str]) -> Dict[str, Any]:
    """
    Create an if/then conditional rule for a filter combination.

    Args:
        mapping: Dict with filter field values and enum name

    Returns:
        Dict with if/then structure for allOf
    """
    # Build the if condition
    if_properties = {}
    required_fields = []

    if "modelSystemType" in mapping:
        if_properties["modelSystemType"] = {"const": mapping["modelSystemType"]}
        required_fields.append("modelSystemType")

    if "modelSpecies" in mapping:
        # modelSpecies can be array, so check if it contains the value
        if_properties["modelSpecies"] = {"const": mapping["modelSpecies"]}
        required_fields.append("modelSpecies")

    if "cellLineCategory" in mapping:
        if_properties["cellLineCategory"] = {"const": mapping["cellLineCategory"]}
        required_fields.append("cellLineCategory")

    if "cellLineGeneticDisorder" in mapping:
        if_properties["cellLineGeneticDisorder"] = {"const": mapping["cellLineGeneticDisorder"]}
        required_fields.append("cellLineGeneticDisorder")

    # Build the then condition - reference the filtered enum
    then_properties = {
        "modelSystemName": {
            "items": {
                "$ref": f"#/$defs/{mapping['enum']}"
            }
        }
    }

    return {
        "if": {
            "properties": if_properties,
            "required": required_fields
        },
        "then": {
            "properties": then_properties
        }
    }


def add_conditionals_to_schema(schema: Dict[str, Any]) -> Dict[str, Any]:
    """
    Add conditional enum filtering to a JSON schema.

    Args:
        schema: The JSON schema dict

    Returns:
        Modified schema with conditionals added
    """
    # Check if this schema has modelSystemName field
    if "properties" not in schema or "modelSystemName" not in schema.get("properties", {}):
        return schema  # No modelSystemName, skip

    print(f"  Adding {len(CONDITIONAL_MAPPINGS)} conditional rules...")

    # Create allOf rules
    conditional_rules = [create_conditional_rule(mapping) for mapping in CONDITIONAL_MAPPINGS]

    # Add to schema
    if "allOf" in schema:
        # Append to existing allOf
        schema["allOf"].extend(conditional_rules)
    else:
        # Create new allOf
        schema["allOf"] = conditional_rules

    # Add the filtered enum definitions to $defs
    if "$defs" not in schema:
        schema["$defs"] = {}

    # Load enum definitions from generated files
    generated_dir = Path("modules/Sample/generated")
    for mapping in CONDITIONAL_MAPPINGS:
        enum_name = mapping["enum"]
        enum_file = generated_dir / f"{enum_name}.yaml"

        if enum_file.exists():
            # Load the YAML file and extract enum values
            import yaml
            with open(enum_file) as f:
                enum_data = yaml.safe_load(f)

            if "enums" in enum_data and enum_name in enum_data["enums"]:
                enum_values = list(enum_data["enums"][enum_name]["permissible_values"].keys())

                # Add to $defs
                schema["$defs"][enum_name] = {
                    "enum": enum_values,
                    "type": "string"
                }

    return schema


def process_schema_file(schema_path: Path) -> bool:
    """
    Process a single JSON schema file.

    Args:
        schema_path: Path to JSON schema file

    Returns:
        True if modified, False otherwise
    """
    print(f"\nProcessing {schema_path.name}...")

    try:
        with open(schema_path) as f:
            schema = json.load(f)

        # Check if this schema needs conditionals
        if "properties" not in schema or "modelSystemName" not in schema.get("properties", {}):
            print("  Skipping (no modelSystemName field)")
            return False

        # Add conditionals
        modified_schema = add_conditionals_to_schema(schema)

        # Write back
        with open(schema_path, 'w') as f:
            json.dump(modified_schema, f, indent=2)

        print("  ✓ Added conditional filtering")
        return True

    except Exception as e:
        print(f"  ✗ Error: {e}")
        return False


def main():
    import argparse

    parser = argparse.ArgumentParser(description='Add conditional enum filtering to JSON schemas')
    parser.add_argument('--schema-dir', default='registered-json-schemas',
                       help='Directory containing JSON schema files')
    parser.add_argument('--dry-run', action='store_true',
                       help='Show what would be done without making changes')

    args = parser.parse_args()

    schema_dir = Path(args.schema_dir)
    if not schema_dir.exists():
        print(f"Error: Schema directory not found: {schema_dir}")
        sys.exit(1)

    print("="*60)
    print("ADDING CONDITIONAL ENUM FILTERING TO JSON SCHEMAS")
    print("="*60)
    print(f"Schema directory: {schema_dir}")
    print(f"Dry run: {args.dry_run}")
    print()

    # Process all JSON schema files
    schema_files = list(schema_dir.glob("*.json"))
    modified_count = 0

    for schema_file in sorted(schema_files):
        if not args.dry_run:
            if process_schema_file(schema_file):
                modified_count += 1
        else:
            # Dry run - just check
            with open(schema_file) as f:
                schema = json.load(f)
            if "properties" in schema and "modelSystemName" in schema.get("properties", {}):
                print(f"Would add conditionals to: {schema_file.name}")
                modified_count += 1

    print("\n" + "="*60)
    print(f"{'DRY RUN - ' if args.dry_run else ''}COMPLETED")
    print("="*60)
    print(f"Modified {modified_count} schema files")


if __name__ == '__main__':
    main()
