#!/usr/bin/env python3
"""
Policy for detecting and repairing mis-cased annotation keys on NF-OSI Synapse
entities (issue #939).

Requires: pyyaml (stdlib otherwise). This module deliberately does NOT import
synapseclient, so every rule that governs a destructive write can be unit
tested offline in CI.

Background
----------
Two unrelated defects leave an entity carrying the same concept under keys that
differ only in casing, and each needs its own classifier:

Rule A - PascalCase schematic labels.
    Every attribute in the schema has two names: a PascalCase ``rdfs:label`` and
    a camelCase ``sms:displayName``. In the legacy ``NF.jsonld``, ``bts:Age``
    carries ``rdfs:label: "Age"`` and ``sms:displayName: "age"``. A legacy
    schematic/DCA submission path keyed annotations off ``rdfs:label``, so
    entities ended up with both ``Age`` and ``age``. The stray form is exactly
    ``canonical[:1].upper() + canonical[1:]``, verified against every stray key
    observed in the wild.

Rule B - case-variant drift.
    Former slot names left behind by schema renames, e.g. ``timePointUnit``
    before it became ``timepointUnit``. These are not derivable from rule A and
    are only found by a case-insensitive collision against the canonical set.

Canonical names come from ``dist/NF.yaml``. ``NF.jsonld`` is legacy and no
longer regenerated by the build; it is useful only as evidence of what the bad
writer produced.
"""

from __future__ import annotations

import argparse
import difflib
import json
import sys
from collections.abc import Iterable, Mapping, Sequence
from dataclasses import dataclass, field
from enum import Enum
from pathlib import Path
from typing import Any

import yaml

CANONICAL_SCHEMA = Path(__file__).resolve().parent.parent / 'dist' / 'NF.yaml'

# Entity properties Synapse owns. A stray key may be *dropped* even when its
# canonical form appears here - removing `Description` does not write to the
# `description` entity property - but it must never be *renamed* into one.
SYNAPSE_RESERVED_FIELDS = frozenset({
    'benefactorId', 'concreteType', 'contentSize', 'contentType', 'createdBy',
    'createdOn', 'currentVersion', 'dataFileHandleId', 'description', 'etag',
    'id', 'modifiedBy', 'name', 'parentId', 'type',
})

# Keys schematic injects into manifests. They are not stray forms of anything
# and must never be rewritten. `Id` in particular is a manifest row UUID, not a
# PascalCase variant of the `id` slot - treating it as one produced 55
# false-positive projects in the first audit pass.
INFRA_KEYS = frozenset({'Id', 'Uuid', 'eTag', 'EntityId', 'entityId'})

# Columns Synapse adds to every entity view. A scope query returns these
# alongside real annotations, so they must be filtered out or the "unrecognised
# key" bucket fills with view metadata and stops being worth reading.
SYNAPSE_VIEW_COLUMNS = frozenset({
    'benefactorId', 'concreteType', 'createdBy', 'createdOn', 'currentVersion',
    'dataFileBucket', 'dataFileConcreteType', 'dataFileHandleId', 'dataFileKey',
    'dataFileMD5Hex', 'dataFileName', 'dataFileSizeBytes', 'description', 'etag',
    'id', 'modifiedBy', 'modifiedOn', 'name', 'parentId', 'path', 'projectId',
    'type', 'versionComment', 'versionLabel', 'versionNumber',
})

#: How close an unrecognised key has to be to a canonical name before it is
#: called a probable typo rather than a legitimate custom annotation. 0.85 was
#: chosen because it catches the real `progrssReportNumber` case without
#: matching unrelated custom keys such as `tissue` or `sampleSite`.
TYPO_SIMILARITY_CUTOFF = 0.85

# Historical aliases the PascalCase rule cannot derive, taken from the legacy
# NF.jsonld label/displayName pairs. `eTag` is the important one: to_stray('etag')
# is 'Etag', so nothing else would catch it. These five have zero hits in the
# wild today and are kept so coverage claims stay honest.
LEGACY_ALIASES = {
    'Breast Cancer': 'breastCancer',
    'Vestibular Schwannoma': 'vestibularSchwannoma',
    'CroissantFileS3Object': 'croissant_file_s3_object',
    'ResourceId': 'Resource_id',
    'eTag': 'etag',
}


class Action(str, Enum):
    """What to do about one key on one entity."""

    SKIP = 'skip'
    DROP_STRAY = 'drop_stray'
    RENAME_STRAY = 'rename_stray'
    REPORT_CONFLICT = 'report_conflict'
    REPORT_RESERVED = 'report_reserved'
    REPORT_RETIRED = 'report_retired'


#: Actions that mutate an entity. Everything else is report-only.
WRITING_ACTIONS = frozenset({Action.DROP_STRAY, Action.RENAME_STRAY})


@dataclass(frozen=True)
class Decision:
    action: Action
    stray_key: str
    canonical_key: str | None
    reason: str
    stray_value: Any = None
    canonical_value: Any = None

    def as_dict(self) -> dict:
        return {
            'action': self.action.value,
            'stray_key': self.stray_key,
            'canonical_key': self.canonical_key,
            'reason': self.reason,
            'stray_value': self.stray_value,
            'canonical_value': self.canonical_value,
        }


@dataclass(frozen=True)
class KeyIndex:
    """Precomputed lookups for both classifiers."""

    #: stray key -> canonical name, from the PascalCase rule plus LEGACY_ALIASES
    stray_index: Mapping[str, str]
    #: lowercased name -> the canonical names that fold to it
    case_index: Mapping[str, frozenset[str]]

    @classmethod
    def build(cls, canon: Iterable[str], aliases: Mapping[str, str] | None = None) -> KeyIndex:
        canon = frozenset(canon)
        aliases = LEGACY_ALIASES if aliases is None else aliases

        stray_index: dict[str, str] = {}
        for name in sorted(canon):
            stray = to_stray(name)
            # Skip names that are already capitalised: to_stray is the identity
            # for them, and mapping `Component` -> `Component` would make the
            # tool try to rename valid data to itself.
            if stray == name:
                continue
            stray_index[stray] = name
        for stray, target in aliases.items():
            stray_index.setdefault(stray, target)

        case_index: dict[str, set[str]] = {}
        for name in canon:
            case_index.setdefault(name.lower(), set()).add(name)

        return cls(
            stray_index=stray_index,
            case_index={k: frozenset(v) for k, v in case_index.items()},
        )


def load_canonical_slots(path: Path | str = CANONICAL_SCHEMA) -> frozenset[str]:
    """Every valid annotation attribute name in the data model.

    Reads both the top-level ``slots:`` block and the inline ``attributes:`` of
    the template classes that declare them instead of referencing slots
    (DataLandscape, PortalDataset, PortalPublication, PortalStudy,
    PublicationTemplate). Omitting the latter would leave the audit blind to
    portal study, dataset and publication annotations.
    """
    with open(path) as handle:
        model = yaml.safe_load(handle)

    names = set(model.get('slots') or {})
    for cls in (model.get('classes') or {}).values():
        if cls and cls.get('attributes'):
            names |= set(cls['attributes'])
    return frozenset(names)


def to_stray(canonical: str) -> str:
    """The PascalCase (``rdfs:label``) form of a canonical slot name."""
    if not canonical:
        return canonical
    return canonical[:1].upper() + canonical[1:]


def resolve_canonical(key: str, *, canon: frozenset[str], index: KeyIndex) -> tuple[str | None, str]:
    """Map an observed annotation key to the canonical slot it corresponds to.

    Returns ``(canonical_name, rule)``, or ``(None, reason)`` when the key does
    not correspond to any canonical slot.
    """
    if key in index.stray_index:
        return index.stray_index[key], 'pascal_label'

    # Rule B. Only accept an unambiguous fold; a key colliding with two
    # canonical names cannot be repaired automatically.
    candidates = index.case_index.get(key.lower(), frozenset()) - {key}
    if len(candidates) == 1:
        return next(iter(candidates)), 'case_variant'
    if len(candidates) > 1:
        return None, 'ambiguous_case_variant'
    return None, 'unknown_key'


def _normalize_scalar(value: Any, *, loose: bool) -> Any:
    if value is None:
        return None
    if isinstance(value, str):
        value = value.strip()
        if loose:
            return _loose_scalar(value)
        return value
    if loose:
        return _loose_scalar(value)
    return value


def _loose_scalar(value: Any) -> Any:
    """Collapse a value to a type-insensitive comparison key."""
    text = str(value).strip().lower()
    try:
        # So 1119 == "1119" and 1.0 == "1", but "x" stays "x".
        return float(text)
    except (TypeError, ValueError):
        return text


def _as_tuple(value: Any, *, loose: bool) -> tuple:
    if value is None:
        return ()
    if isinstance(value, (list, tuple)):
        items = [_normalize_scalar(v, loose=loose) for v in value]
    else:
        items = [_normalize_scalar(value, loose=loose)]
    if loose:
        # Order-insensitive only in loose mode; see values_equivalent.
        return tuple(sorted(items, key=repr))
    return tuple(items)


def is_empty_value(value: Any) -> bool:
    """True for annotation values carrying no information.

    ``0`` and ``False`` are NOT empty - dropping them as if absent loses data.
    """
    if value is None:
        return True
    if isinstance(value, str):
        return not value.strip()
    if isinstance(value, (list, tuple)):
        return all(is_empty_value(v) for v in value) if value else True
    return False


def values_equivalent(left: Any, right: Any, *, loose: bool = False) -> bool:
    """Whether two annotation values carry the same information.

    Strict mode (the default) treats a scalar and a one-item list as the same,
    strips surrounding whitespace, and compares numbers numerically - so
    ``[1]`` and ``[1.0]`` match - but keeps types and list order significant.
    That makes ``IndividualID: [1119]`` (INTEGER) and ``individualID: ["1119"]``
    (STRING) a reportable conflict rather than a silent delete.

    Loose mode additionally ignores type and list order, and is what
    ``--loose-compare`` opts into after a human has reviewed the conflicts.
    """
    return _as_tuple(left, loose=loose) == _as_tuple(right, loose=loose)


def decide(
    key: str,
    annotations: Mapping[str, Any],
    *,
    canon: frozenset[str],
    index: KeyIndex,
    reserved: frozenset[str] = SYNAPSE_RESERVED_FIELDS,
    infra: frozenset[str] = INFRA_KEYS,
    loose_compare: bool = False,
) -> Decision:
    """Classify one key on one entity.

    Rule order is load bearing and documented per branch below. The bias is
    always toward reporting: a key is only queued for a write when the outcome
    is unambiguous.
    """
    stray_value = annotations.get(key)

    # 1. Schematic infrastructure. Never a stray form of anything.
    if key in infra:
        return Decision(Action.SKIP, key, None, 'infra_key', stray_value)

    # 2. Already the canonical name (includes the 9 canonical slots that legitimately
    #    start uppercase, such as `Component` and `Filename`).
    if key in canon:
        return Decision(Action.SKIP, key, None, 'canonical', stray_value)

    canonical, rule = resolve_canonical(key, canon=canon, index=index)
    if canonical is None:
        # 3. Not attributable to any slot. Reported by the audit, never rewritten.
        return Decision(Action.SKIP, key, None, rule, stray_value)

    # 4. An empty stray is pure noise. This has to precede every value
    #    comparison, or an empty stray sitting next to a populated canonical is
    #    misfiled as a conflict and the noise never gets cleaned up. Dropping is
    #    safe even when the canonical name is reserved, because removing the
    #    stray key writes nothing to the reserved entity property.
    if is_empty_value(stray_value):
        return Decision(Action.DROP_STRAY, key, canonical, 'empty_stray_value', stray_value)

    if canonical in annotations:
        canonical_value = annotations[canonical]
        # 5. Both present. Only a drop or a report is possible here, so a
        #    reserved canonical name is not a concern.
        if values_equivalent(stray_value, canonical_value):
            return Decision(Action.DROP_STRAY, key, canonical, 'values_equivalent',
                            stray_value, canonical_value)
        if values_equivalent(stray_value, canonical_value, loose=True):
            action = Action.DROP_STRAY if loose_compare else Action.REPORT_CONFLICT
            return Decision(action, key, canonical, 'type_coercion', stray_value, canonical_value)
        if is_empty_value(canonical_value):
            return Decision(Action.REPORT_CONFLICT, key, canonical, 'canonical_empty',
                            stray_value, canonical_value)
        return Decision(Action.REPORT_CONFLICT, key, canonical, 'values_differ',
                        stray_value, canonical_value)

    # The canonical key is absent, so the only repair is a rename - which means
    # writing to the canonical name, and every guard below protects that write.

    # 6. Renaming into a Synapse-owned property is never allowed.
    if canonical in reserved:
        return Decision(Action.REPORT_RESERVED, key, canonical, 'reserved_target', stray_value)

    # 7. Renaming into a slot the schema no longer defines would resurrect a dead
    #    field into the portal namespace.
    if canonical not in canon:
        return Decision(Action.REPORT_RETIRED, key, canonical, 'retired_target', stray_value)

    # 8. A third casing of the same concept is also present, so a rename would
    #    silently clobber one of them. Real case: syn8012530 carries both
    #    `TimePointUnit` and `timePointUnit`.
    siblings = {
        other for other in annotations
        if other != key and other.lower() == canonical.lower()
    }
    if siblings:
        return Decision(Action.REPORT_CONFLICT, key, canonical, 'multi_variant', stray_value,
                        {s: annotations[s] for s in sorted(siblings)})

    return Decision(Action.RENAME_STRAY, key, canonical, f'orphan_{rule}', stray_value)


def decide_entity(annotations: Mapping[str, Any], **kwargs) -> list[Decision]:
    """Classify every key on one entity, in a stable order."""
    return [decide(key, annotations, **kwargs) for key in sorted(annotations)]


def apply_decisions(
    annotations: Mapping[str, Any],
    decisions: Sequence[Decision],
) -> dict[str, Any]:
    """Return a new annotation dict with the writing decisions applied.

    Pure: the input is never mutated. Keys not named by a writing decision are
    copied verbatim - notably their values are NOT list-normalized, because
    rewriting values the caller did not ask to touch would make the
    verification pass's "nothing else changed" assertion meaningless.

    Raises rather than silently no-oping when a decision no longer matches the
    data, so a stale plan cannot report success without having changed anything.
    """
    result = dict(annotations)
    for decision in decisions:
        if decision.action not in WRITING_ACTIONS:
            continue
        if decision.stray_key not in result:
            raise KeyError(
                f'{decision.action.value} for absent key {decision.stray_key!r}; plan is stale'
            )
        if decision.action is Action.DROP_STRAY:
            del result[decision.stray_key]
            continue

        # RENAME_STRAY
        target = decision.canonical_key
        if target is None:
            raise ValueError(f'rename of {decision.stray_key!r} has no canonical target')
        if target in result:
            raise ValueError(
                f'refusing to rename {decision.stray_key!r} onto existing key {target!r}'
            )
        value = result.pop(decision.stray_key)
        result[target] = value if isinstance(value, list) else [value]
    return result


def _closest_canonical(key: str, sorted_canon: Sequence[str]) -> str | None:
    """The canonical name an unrecognised key is probably a misspelling of."""
    matches = difflib.get_close_matches(key, sorted_canon, n=1, cutoff=TYPO_SIMILARITY_CUTOFF)
    return matches[0] if matches else None


@dataclass
class InventorySummary:
    """Project-level triage from a key inventory, before any entity is read."""

    duplicates: dict[str, str] = field(default_factory=dict)
    orphans: dict[str, str] = field(default_factory=dict)
    case_variants: dict[str, str] = field(default_factory=dict)
    reserved: dict[str, str] = field(default_factory=dict)
    near_misses: dict[str, str] = field(default_factory=dict)
    unknown: list[str] = field(default_factory=list)

    @property
    def has_findings(self) -> bool:
        return bool(self.duplicates or self.orphans or self.case_variants)

    def as_dict(self) -> dict:
        return {
            'duplicates': self.duplicates,
            'orphans': self.orphans,
            'case_variants': self.case_variants,
            'reserved': self.reserved,
            'near_misses': self.near_misses,
            'unknown': sorted(self.unknown),
        }


def classify_key_inventory(
    present_keys: Iterable[str],
    *,
    canon: frozenset[str],
    index: KeyIndex,
    reserved: frozenset[str] = SYNAPSE_RESERVED_FIELDS,
    infra: frozenset[str] = INFRA_KEYS,
    view_columns: frozenset[str] = SYNAPSE_VIEW_COLUMNS,
    detect_typos: bool = True,
) -> InventorySummary:
    """Triage a whole project's annotation-key inventory.

    This works from key *names* only, so it can run off one
    ``/column/view/scope/async`` call per project with no entity reads. It
    reports presence, not counts: one bad file in 6,000 looks identical to
    wholesale corruption, so an entity-level drill-down is still required before
    judging scale or writing anything.
    """
    present = set(present_keys)
    summary = InventorySummary()
    sorted_canon = sorted(canon)

    for key in sorted(present):
        if key in infra or key in canon or key in view_columns:
            continue
        canonical, rule = resolve_canonical(key, canon=canon, index=index)
        if canonical is None:
            match = _closest_canonical(key, sorted_canon) if detect_typos else None
            if match:
                # A probable misspelling, e.g. `progrssReportNumber`. Surfaced
                # separately because it is a real data bug, but never queued for
                # a write: a typo is a guess, not a derivable mapping.
                summary.near_misses[key] = match
            else:
                summary.unknown.append(key)
            continue
        if canonical in reserved and canonical not in present:
            summary.reserved[key] = canonical
            continue
        if rule == 'case_variant':
            summary.case_variants[key] = canonical
        elif canonical in present:
            summary.duplicates[key] = canonical
        else:
            summary.orphans[key] = canonical
    return summary


def main(argv: Sequence[str] | None = None) -> int:
    """Inspect the derived key maps without touching Synapse."""
    parser = argparse.ArgumentParser(description=__doc__.split('\n')[1])
    parser.add_argument('--schema', default=str(CANONICAL_SCHEMA), help='path to dist/NF.yaml')
    parser.add_argument('--format', choices=['text', 'json'], default='text')
    args = parser.parse_args(argv)

    canon = load_canonical_slots(args.schema)
    index = KeyIndex.build(canon)
    payload = {
        'canonical_slots': len(canon),
        'stray_keys': len(index.stray_index),
        'self_pascal_slots': sorted(c for c in canon if to_stray(c) == c),
        'reserved_targets': sorted(
            stray for stray, target in index.stray_index.items() if target in SYNAPSE_RESERVED_FIELDS
        ),
        'infra_keys': sorted(INFRA_KEYS),
    }
    if args.format == 'json':
        print(json.dumps(payload, indent=2))
    else:
        print(f"canonical slots      : {payload['canonical_slots']}")
        print(f"derived stray keys   : {payload['stray_keys']}")
        print(f"self-pascal slots    : {', '.join(payload['self_pascal_slots'])}")
        print(f"never auto-renamable : {', '.join(payload['reserved_targets'])}")
        print(f"infra keys (skipped) : {', '.join(payload['infra_keys'])}")
    return 0


if __name__ == '__main__':
    sys.exit(main())
