#!/usr/bin/env python3
"""
Fix missing sms:displayName fields in NF.jsonld after schematic conversion.

This script addresses the issue where schematic schema convert removes sms:displayName
fields for certain entries, particularly those with spaces in their names.
"""

import json
import sys
from pathlib import Path


def extract_display_names_from_retold_output(retold_jsonld_path: str) -> dict:
    """Extract sms:displayName mappings from retold-generated JSON-LD."""
    with open(retold_jsonld_path, 'r') as f:
        data = json.load(f)
    
    display_names = {}
    for entry in data.get('@graph', []):
        if '@id' in entry and 'sms:displayName' in entry:
            entry_id = entry['@id']
            display_name = entry['sms:displayName']
            display_names[entry_id] = display_name
    
    return display_names


def fix_missing_display_names(nf_jsonld_path: str, display_names: dict) -> int:
    """Add missing sms:displayName fields to NF.jsonld entries."""
    with open(nf_jsonld_path, 'r') as f:
        data = json.load(f)
    
    fixed_count = 0
    for entry in data.get('@graph', []):
        if '@id' in entry:
            entry_id = entry['@id']
            
            # If this entry is missing sms:displayName but we have one from retold
            if 'sms:displayName' not in entry and entry_id in display_names:
                entry['sms:displayName'] = display_names[entry_id]
                fixed_count += 1
                print(f"Fixed missing displayName for: {entry_id}")
    
    # Write back the fixed JSON-LD
    with open(nf_jsonld_path, 'w') as f:
        json.dump(data, f, indent=2)
    
    return fixed_count


def main():
    if len(sys.argv) != 3:
        print("Usage: fix_display_names.py <retold_jsonld> <nf_jsonld>")
        print("  retold_jsonld: Path to JSON-LD generated by retold (with correct displayNames)")
        print("  nf_jsonld: Path to NF.jsonld to fix (after schematic conversion)")
        sys.exit(1)
    
    retold_jsonld_path = sys.argv[1]
    nf_jsonld_path = sys.argv[2]
    
    if not Path(retold_jsonld_path).exists():
        print(f"Error: {retold_jsonld_path} does not exist")
        sys.exit(1)
    
    if not Path(nf_jsonld_path).exists():
        print(f"Error: {nf_jsonld_path} does not exist")
        sys.exit(1)
    
    print("Extracting display names from retold output...")
    display_names = extract_display_names_from_retold_output(retold_jsonld_path)
    print(f"Found {len(display_names)} display name mappings")
    
    print("Fixing missing display names in NF.jsonld...")
    fixed_count = fix_missing_display_names(nf_jsonld_path, display_names)
    
    print(f"Fixed {fixed_count} missing displayName fields")


if __name__ == '__main__':
    main()