name: Dispatch downstream dev

on:
  release:
    types: [published]

env:
  REPO: nf-osi/NF_data_curator # DCA repo of community
  REF_DEV: refs/heads/develop # ref to develop branch
  REPO_RAW: https://raw.githubusercontent.com/nf-osi/nf-metadata-dictionary
  SRC_FILE: NF.jsonld

jobs:
  dispatch-downstream-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Generate input payload
        id: payload
        run: |
          sudo apt install jq
          URL=$REPO_RAW/$GITHUB_REF_NAME/$SRC_FILE
          INPUT=$(jq -n -c --arg url "$URL" '{ source: $url}')
          echo "::set-output name=INPUT::$INPUT"
      - uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Update source model for dev
          repo: $REPO
          ref: $REF_DEV
          token: ${{ secrets.SERVICE_TOKEN }}
          inputs: ${{ steps.payload.outputs.INPUT }}
