# Trigger dcc-site to create a PR for its `main` self that pulls in data model changes into study-schema drop-down options
# whenever there are pushes to `main` with relevant model changes

name: Sync dcc-site

on:
  push:
    branches: 
      - main
    paths:
      - NF.jsonld
      
env:
  REPO: nf-osi/dcc-site
  REF: refs/heads/main
      
jobs:
  trigger-sync:
    runs-on: ubuntu-latest
    steps:
    
      - uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Handle data model update
          repo: ${{ env.REPO }}
          ref: ${{ env.REF }}
          token: ${{ secrets.SERVICE_TOKEN }}
