# When a commit is merged to `main` that includes changes to modules/*, this will "followup" to regenerate the JSON schemas.
# ONLY if a modified schema file is detected will a PR be triggered.
# For example, PortalDataset only has dependencies on certain things like Assay, Species, Portal etc., hence changes in other parts of the model won't actually change the file.
# There is a separate job to update registration of the schemas with the Synapse schema registry when this PR is merged.
 

name: register-json-schema

on:

  push:
    branches: 
      - main
    paths:
      - modules/* # ignore changes in docs, workflows, etc.
  
jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Regen dataset and superdataset with potentially new assay values
        run: |
          make Dataset
          make Superdataset

      - name: Install LinkML and regenerate PortalDataset and PortalStudy
        run: |
          pip install linkml
          make PortalDataset
          make PortalStudy
      
      - name: Check changes in any of the schema files
        run: |
          if git diff-index --quiet HEAD --; then
            echo 'MAKE_PR=true' >> $GITHUB_ENV
          else
            echo 'MAKE_PR=false' >> $GITHUB_ENV
          fi
      
      - name: Commit files for PR only if there are changes
        if: ${{ env.MAKE_PR == true }}
        run: |
          git config --local user.email "57509804+nfosi-service@users.noreply.github.com"
          git config --local user.name "nfosi-service"
          git add .
          git commit -m "Update registered JSON schemas"
      
      - name: Push changes
        if: ${{ env.MAKE_PR == true }}
        uses: ad-m/github-push-action@master
        with:
          branch: registered-schemas-update/${{ github.run_id }} # name of branch that will be created for update
          github_token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Make a PR with appropriate tags
        if: ${{ env.MAKE_PR == true }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh pr create -B main -H registered-schemas-update/${{ github.run_id }} --title "Registered schemas update" --body "Some JSON schemas have been rebuilt"           
